services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VUE_APP_API_DOMAIN: ${VUE_APP_API_DOMAIN}
    ports:
      - 4000:80
    restart: always
    pull_policy: build