services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VUE_APP_ADMIN_PASSWORD: ${VUE_APP_ADMIN_PASSWORD}
    ports:
      - 4000:80
    restart: always
    pull_policy: build